name: "\U0001F41E Bug report"
description: Create a report to help us improve macOS Post-Install
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in as much of the template below as you're able.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: The copy button doesn't work on mobile when...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
      placeholder: Drag and drop images here...
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: Safari
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: macOS Tahoe 26.2
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here.
      placeholder: Additional information...
